In [2]:
import pandas as pd

In [2]:
train1 = pd.read_csv("train1.csv")
test1 = pd.read_csv("test1.csv")
val = pd.read_csv("val.csv")

In [3]:
drug_labels_smiles_final = pd.read_csv("tox_labels_smiles_final.csv")
drug_labels_smiles_final

,Unnamed: 0,drug,withdrawn,withdrawn_cards,withdrawn_liver,withdrawn_neuro,ATC_cards,ATC_liver,ATC_neuro,smiles
0,0,chembl479,1,1,0,0,0,0,1,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2
1,1,chembl12713,1,1,0,0,0,0,1,O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccc(Cl)cc...
2,2,chembl583,1,1,0,0,0,0,0,Cc1c(F)c(N2CCNC(C)C2)cc2c1c(=O)c(C(=O)O)cn2C1CC1
3,3,chembl17157,1,1,0,0,0,0,0,CC(C)(C)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccc...
4,4,chembl121,1,1,0,0,0,0,0,CN(CCOc1ccc(CC2SC(=O)NC2=O)cc1)c1ccccn1
...,...,...,...,...,...,...,...,...,...,...
1290,1084,tirbanibulin,0,0,0,0,0,0,0,O=C(Cc1ccc(-c2ccc(OCCN3CCOCC3)cc2)cn1)NCc1ccccc1
1291,1085,naproxen oral,0,0,0,0,0,0,0,COc1ccc2cc([C@H](C)C(=O)O)ccc2c1
1292,1086,fingolimod hcl,0,0,0,0,0,0,0,CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1.Cl
1293,1087,pyrazinamide tablet,0,0,0,0,0,0,0,NC(=O)c1cnccn1
1294,1088,abacavir sulfate- dolutegravir sodium- lamivudine,0,0,0,0,0,0,0,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1....

In [4]:
drug_labels_smiles_final = drug_labels_smiles_final.loc[:, ['drug', 'withdrawn', 'smiles']]

In [5]:
drug_labels_smiles_final.columns = ['drug', 'withdrawn_class', 'smiles']

In [6]:
drug_labels_smiles_final

,drug,withdrawn_class,smiles
0,chembl479,1,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2
1,chembl12713,1,O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccc(Cl)cc...
2,chembl583,1,Cc1c(F)c(N2CCNC(C)C2)cc2c1c(=O)c(C(=O)O)cn2C1CC1
3,chembl17157,1,CC(C)(C)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccc...
4,chembl121,1,CN(CCOc1ccc(CC2SC(=O)NC2=O)cc1)c1ccccn1
...,...,...,...
1290,tirbanibulin,0,O=C(Cc1ccc(-c2ccc(OCCN3CCOCC3)cc2)cn1)NCc1ccccc1
1291,naproxen oral,0,COc1ccc2cc([C@H](C)C(=O)O)ccc2c1
1292,fingolimod hcl,0,CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1.Cl
1293,pyrazinamide tablet,0,NC(=O)c1cnccn1
1294,abacavir sulfate- dolutegravir sodium- lamivudine,0,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1....

In [7]:
train1.columns = ['drug']

In [8]:
merged_train = train1.merge(drug_labels_smiles_final, on='drug', how='inner')

In [9]:
test1.columns = ['drug']
merged_test = test1.merge(drug_labels_smiles_final, on='drug')
merged_test

,drug,withdrawn_class,smiles
0,chembl2105233,1,C=CCC1(CC(C)O)C(=O)NC(=O)NC1=O
1,chembl146095,1,O=C(OCC(O)CO)c1ccccc1Nc1ccnc2cc(Cl)ccc12
2,chembl2106829,1,Cc1ccccc1-n1c(C)nc2ccccc2c1=O.Cl
3,chembl282724,1,Cc1cc2c(cc1CC(=O)c1sccc1S(=O)(=O)Nc1onc(C)c1Cl...
4,chembl462547,1,CCOC(N)=O
5,chembl1213351,1,CCC(=O)O[C@](Cc1ccccc1)(c1ccccc1)[C@H](C)CN(C)C
6,chembl53292,1,Cc1cc(NC(=O)C2=C(O)c3ccccc3S(=O)(=O)N2C)no1
7,chembl1256841,1,O=C(CCNNC(=O)c1ccncc1)NCc1ccccc1
8,chembl1291,1,CC(=O)Oc1c(C)cc(OCC(O)CNC(C)C)c(C)c1C
9,chembl1200695,1,CC(N)C(O)c1ccccc1.Cl
10,chembl21869,1,O=C(Nc1ccc(Br)cc1)c1cc(Br)ccc1O
11,chembl3187246,1,CN(C)CCN(Cc1cccs1)c1ccccn1.CN(C)CCN(Cc1cccs1)c...
12,chembl646,1,Cc1nnc2n1-c1ccc(Cl)cc1C(c1ccccc1Cl)=NC2
13,chembl37744,1,CN(C)C/C=C(/c1ccc(Br)cc1)c1cccnc1
14,chembl3188576,1,CN[C@@H]1[C@H](O[C@H]2[C@H](O[C@H]3[C@H](O)[C@...
15,chembl13376,1,COc1ccc2c(C(=O)c3ccc(Cl)cc3)c(C)n(CC(=O)O)c2c1
16,chembl277100,1,CC1CN(c2cc3c(cc2F)c(=O)c(C(=O)O)cn3-c2ccc(F)cc...
17,chembl522038,1,CCOC(=O)CN[C@@H](C(=O)N1CC[C@H]1C(=O)NCc1ccc(/...
18,chembl412873,1,C1CCN2C[C@H]3C[C@H](CN4CCCC[C@@H]34)[C@H]2C1
19,chembl400599,1,CC(Cc1cccc(C(F)(F)F)c1)NCCOC(=O)c1ccccc1
20,diclofenac sodium topical gel- 1%-,0,O=C([O-])Cc1ccccc1Nc1c(Cl)cccc1Cl.[Na+]
21,ethotoin,0,CCN1C(=O)NC(c2ccccc2)C1=O
22,toremifene citrate,0,CN(C)CCOc1ccc(/C(=C(/CCCl)c2ccccc2)c2ccccc2)cc...
23,epinastine hydrochloride,0,Cl.NC1=NCC2c3ccccc3Cc3ccccc3N12
24,tecovirimat monohydrate,0,O.O=C(NN1C(=O)[C@@H]2[C@@H]3C=C[C@@H]([C@H]4C[...
25,selexipag,0,CC(C)N(CCCCOCC(=O)NS(C)(=O)=O)c1cnc(-c2ccccc2)...
26,levalbuterol tartrate,0,CC(C)(C)NC[C@H](O)c1ccc(O)c(CO)c1.CC(C)(C)NC[C...
27,cyclobenzaprine,0,CN(C)CCC=C1c2ccccc2C=Cc2ccccc21
28,adefovir dipivoxil,0,CC(C)(C)C(=O)OCOP(=O)(COCCn1cnc2c(N)ncnc21)OCO...
29,fluocinolone acetonide,0,CC1(C)O[C@@H]2C[C@H]3[C@@H]4C[C@H](F)C5=CC(=O)...
30,anagrelide,0,O=C1CN2Cc3c(ccc(Cl)c3Cl)N=C2N1
31,isoniazid,0,NNC(=O)c1ccncc1
32,tigecycline,0,CN(C)c1cc(NC(=O)CNC(C)(C)C)c(O)c2c1C[C@H]1C[C@...
33,phenazopyridine hydrochloride,0,Cl.Nc1ccc(/N=N/c2ccccc2)c(N)n1
34,valacyclovir,0,CC(C)[C@H](N)C(=O)OCCOCn1cnc2c(=O)nc(N)[nH]c21
35,enalapril,0,CCOC(=O)[C@H](CCc1ccccc1)N[C@@H](C)C(=O)N1CCC[...
36,anagrelide hydrochloride,0,Cl.O=C1CN2Cc3c(ccc(Cl)c3Cl)N=C2N1
37,cetirizine hydrochloride,0,Cl.Cl.O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1
38,fedratinib hydrochloride,0,Cc1cnc(Nc2ccc(OCCN3CCCC3)cc2)nc1Nc1cccc(S(=O)(...
39,enfuvirtide,0,CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...

In [10]:
val.columns = ['drug']
merged_val = val.merge(drug_labels_smiles_final, on='drug')
merged_val

,drug,withdrawn_class,smiles
0,chembl395110,1,CN1CCCC(CN2c3ccccc3Sc3ccccc32)C1
1,chembl311498,1,Oc1cc(O)c2c(c1)O[C@H](c1ccc(O)c(O)c1)[C@@H](O)C2
2,chembl16080,1,CC(Cl)(Cl)Cl
3,chembl111,1,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...
4,chembl24072,1,CC(Cc1ccccc1)NCCC(c1ccccc1)c1ccccc1
5,chembl2104793,1,CCCC(C(=O)c1ccc(C)cc1)N1CCCC1.Cl
6,chembl1998966,1,C/C(=N\O)c1ccc(OCC(=O)N2CCCCC2)cc1
7,chembl448,1,CCCC(C)C1(CC)C(=O)NC(=O)NC1=O
8,chembl447,1,C=CCC1(C(C)CCC)C(=O)NC(=O)NC1=O
9,chembl1201201,1,CN[C@@H](C)Cc1ccccc1
10,chembl1729,1,COc1cc(N)c(Cl)cc1C(=O)NC1CCN(CCCOc2ccc(F)cc2)C...
11,chembl1204165,1,C[C@H](CCc1ccccc1)NC[C@H](O)c1ccc(O)c(C(N)=O)c...
12,chembl2107253,1,COc1cc([N-]S(=O)(=O)c2ccc(N)cc2)nc(OC)n1.[Na+]
13,chembl3142541,1,CCCCOC(=O)c1ccc(N)cc1.CCCCOC(=O)c1ccc(N)cc1.O=...
14,chembl70046,1,O=c1[nH]c(=O)n([C@@H]2O[C@H](CO)[C@@H](O)[C@@H...
15,chembl3989830,1,CC(C)CC(N(C)C)C1(c2ccc(Cl)cc2)CCC1.Cl.O
16,chembl404108,1,Cc1ccc(Nc2c(F)cccc2Cl)c(CC(=O)O)c1
17,chembl1516474,1,CCCCCNC(=N)N/N=C/c1c[nH]c2ccc(OC)cc12.O=C(O)/C...
18,chembl752,1,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...
19,chembl32800,1,CC(Cc1ccc(O)cc1)NCC(O)c1cc(O)cc(O)c1
20,lovastatin,0,CC[C@H](C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C...
21,mecamylamine hydrochloride,0,CNC1(C)C2CCC(C2)C1(C)C.Cl
22,hydrocortisone,0,C[C@]12CCC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C...
23,tivozanib,0,COc1cc2nccc(Oc3ccc(NC(=O)Nc4cc(C)on4)c(Cl)c3)c...
24,ganciclovir,0,Nc1nc2c(ncn2COC(CO)CO)c(=O)[nH]1
25,danazol,0,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=Cc5oncc5C[C@]4(...
26,atomoxetine hydrochloride,0,CNCC[C@@H](Oc1ccccc1C)c1ccccc1.Cl
27,carfilzomib,0,CC(C)C[C@H](NC(=O)[C@H](CCc1ccccc1)NC(=O)CN1CC...
28,acetylsalicylic acid,0,CC(=O)Oc1ccccc1C(=O)O
29,rocuronium,0,C=CC[N+]1([C@H]2C[C@H]3[C@@H]4CC[C@H]5C[C@H](O...
30,desvenlafaxine,0,CN(C)CC(c1ccc(O)cc1)C1(O)CCCCC1
31,paclitaxel,0,CC(=O)O[C@H]1C(=O)[C@@]2(C)[C@H]([C@H](OC(=O)c...
32,phenylephrine hydrochloride,0,CNC[C@H](O)c1cccc(O)c1.Cl
33,adenosine,0,Nc1ncnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O
34,sotalol hydrochloride,0,CC(C)NCC(O)c1ccc(NS(C)(=O)=O)cc1.Cl
35,fluphenazine hydrochloride,0,Cl.Cl.OCCN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc...
36,vardenafil,0,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC...
37,azathioprine,0,Cn1cnc([N+](=O)[O-])c1Sc1ncnc2[nH]cnc12
38,brivaracetam,0,CCC[C@@H]1CC(=O)N([C@@H](CC)C(N)=O)C1
39,ethionamide,0,CCc1cc(C(N)=S)ccn1

In [11]:
merged_train.to_csv("merged_train.csv")
merged_test.to_csv("merged_test.csv")
merged_val.to_csv("merged_val.csv")

### New Merged dataset creation for imbalanced dataset from the seed_0 as an example

In [7]:
train = pd.read_csv("/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_0/merged_train.csv")
test = pd.read_csv("/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_0/merged_test.csv")
val = pd.read_csv("/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_0/merged_val.csv")

In [3]:
drug_labels_smiles_final = pd.read_csv("tox_labels_smiles_final.csv")
drug_labels_smiles_final

,Unnamed: 0,drug,withdrawn,withdrawn_cards,withdrawn_liver,withdrawn_neuro,ATC_cards,ATC_liver,ATC_neuro,smiles
0,0,chembl479,1,1,0,0,0,0,1,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2
1,1,chembl12713,1,1,0,0,0,0,1,O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccc(Cl)cc...
2,2,chembl583,1,1,0,0,0,0,0,Cc1c(F)c(N2CCNC(C)C2)cc2c1c(=O)c(C(=O)O)cn2C1CC1
3,3,chembl17157,1,1,0,0,0,0,0,CC(C)(C)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccc...
4,4,chembl121,1,1,0,0,0,0,0,CN(CCOc1ccc(CC2SC(=O)NC2=O)cc1)c1ccccn1
...,...,...,...,...,...,...,...,...,...,...
1290,1084,tirbanibulin,0,0,0,0,0,0,0,O=C(Cc1ccc(-c2ccc(OCCN3CCOCC3)cc2)cn1)NCc1ccccc1
1291,1085,naproxen oral,0,0,0,0,0,0,0,COc1ccc2cc([C@H](C)C(=O)O)ccc2c1
1292,1086,fingolimod hcl,0,0,0,0,0,0,0,CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1.Cl
1293,1087,pyrazinamide tablet,0,0,0,0,0,0,0,NC(=O)c1cnccn1
1294,1088,abacavir sulfate- dolutegravir sodium- lamivudine,0,0,0,0,0,0,0,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1....

In [4]:
drug_labels_smiles_final = drug_labels_smiles_final.loc[:, ['drug', 'withdrawn', 'smiles']]

In [5]:
drug_labels_smiles_final.columns = ['drug', 'withdrawn_class', 'smiles']

In [6]:
drug_labels_smiles_final

,drug,withdrawn_class,smiles
0,chembl479,1,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2
1,chembl12713,1,O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccc(Cl)cc...
2,chembl583,1,Cc1c(F)c(N2CCNC(C)C2)cc2c1c(=O)c(C(=O)O)cn2C1CC1
3,chembl17157,1,CC(C)(C)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccc...
4,chembl121,1,CN(CCOc1ccc(CC2SC(=O)NC2=O)cc1)c1ccccn1
...,...,...,...
1290,tirbanibulin,0,O=C(Cc1ccc(-c2ccc(OCCN3CCOCC3)cc2)cn1)NCc1ccccc1
1291,naproxen oral,0,COc1ccc2cc([C@H](C)C(=O)O)ccc2c1
1292,fingolimod hcl,0,CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1.Cl
1293,pyrazinamide tablet,0,NC(=O)c1cnccn1
1294,abacavir sulfate- dolutegravir sodium- lamivudine,0,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1....

In [10]:
train

                                                 smiles  withdrawn_class
0                 CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2                1
1     O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccc(Cl)cc...                1
2      Cc1c(F)c(N2CCNC(C)C2)cc2c1c(=O)c(C(=O)O)cn2C1CC1                1
3     CC(C)(C)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccc...                1
4               CN(CCOc1ccc(CC2SC(=O)NC2=O)cc1)c1ccccn1                1
...                                                 ...              ...
1030   O=C(Cc1ccc(-c2ccc(OCCN3CCOCC3)cc2)cn1)NCc1ccccc1                0
1031                   COc1ccc2cc([C@H](C)C(=O)O)ccc2c1                0
1032                  CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1.Cl                0
1033                                     NC(=O)c1cnccn1                0
1034  Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1....                0

[1035 rows x 2 columns]

In [24]:
drug_labels_smiles_final

,drug,withdrawn_class,smiles
0,chembl479,1,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2
1,chembl12713,1,O=C1NCCN1CCN1CCC(c2cn(-c3ccc(F)cc3)c3ccc(Cl)cc...
2,chembl583,1,Cc1c(F)c(N2CCNC(C)C2)cc2c1c(=O)c(C(=O)O)cn2C1CC1
3,chembl17157,1,CC(C)(C)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccc...
4,chembl121,1,CN(CCOc1ccc(CC2SC(=O)NC2=O)cc1)c1ccccn1
...,...,...,...
1290,tirbanibulin,0,O=C(Cc1ccc(-c2ccc(OCCN3CCOCC3)cc2)cn1)NCc1ccccc1
1291,naproxen oral,0,COc1ccc2cc([C@H](C)C(=O)O)ccc2c1
1292,fingolimod hcl,0,CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1.Cl
1293,pyrazinamide tablet,0,NC(=O)c1cnccn1
1294,abacavir sulfate- dolutegravir sodium- lamivudine,0,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1....

In [27]:
train_smiles = train.merge(drug_labels_smiles_final, on = ['smiles', 'withdrawn_class'], how = 'inner')

In [30]:
train_smiles.drop_duplicates()[['drug', 'withdrawn_class', 'smiles']].to_csv("merged_train.csv")

In [31]:
val_smiles = val.merge(drug_labels_smiles_final, on = ['smiles', 'withdrawn_class'], how = 'inner')

In [32]:
val_smiles.drop_duplicates()[['drug', 'withdrawn_class', 'smiles']].to_csv("merged_val.csv")

In [33]:
test_smiles = val.merge(drug_labels_smiles_final, on = ['smiles', 'withdrawn_class'], how = 'inner')

In [34]:
test_smiles.drop_duplicates()[['drug', 'withdrawn_class', 'smiles']].to_csv("merged_test.csv")