# Imports and Const

In [1]:
import os
import pandas as pd
import random
import math

where is the data located

In [2]:
based_data_path = '/Users/alexwang/Documents/GitHub/withDRAWN'

# Prep Data

This step converts our data to the format t5chem expects to receive

In [3]:
def load_labels(label_key_number, random_seed, train_percent, test_percent):
    '''loads drugs corresponding to a ballanced training and two test sets

    Input:
    label_key_number (int)- column in the label file to use as the labels
    random_seed (int) - controls the randomness for replicability if desired
    train_percent (float) - percent of the set used for testing, recomend 0.9 or less

    Output: (train, test1, test2, Ltrain, Ltest1, Ltest2) (tuple of lists) lists of labels and lists of drug names corresponding to a ballanced training and two test sets
    '''
    positive = []
    negative = []
    with open('tox_labels.csv') as fo:
        i = 0 
        for line in fo:
            if i != 0: 
                split_line = line[:-1].split(',')
                if split_line[label_key_number] == '1':
                    positive.append(split_line[0].lower())
                else:
                    negative.append(split_line[0].lower())
            i += 1

    random.seed(random_seed)
    # the data is not balanced here contrary to the old tox pred.py file, it follows the load labels method in the simple tox pred.py file
    rearrange_positive = random.sample(positive, len(positive))
    rearrange_negative = random.sample(negative, len(negative))

    number_pos1 = math.floor(len(positive)*(train_percent))
    number_neg1 = math.floor(len(negative)*(train_percent))

    number_postest = math.floor(len(positive)*(test_percent))
    number_negtest = math.floor(len(negative)*(test_percent))

    train1 = rearrange_positive[:number_pos1] + rearrange_negative[:number_neg1] 
    test1 = rearrange_positive[number_pos1:number_pos1+ number_postest] + rearrange_negative[number_neg1:number_neg1+number_negtest]
    test2 = rearrange_positive[number_pos1+ number_postest:] + rearrange_negative[number_neg1+number_negtest:]
    

    Ltrain1 = [1]*len(rearrange_positive[:number_pos1]) + [0]*len(rearrange_negative[:number_neg1])
    Ltest1 = [1]*len(rearrange_positive[number_pos1:number_pos1+number_postest]) + [0]*len(rearrange_negative[number_neg1:number_neg1+number_negtest])
    Ltest2 = [1]*len(rearrange_positive[number_pos1+number_postest:]) + [0]*len(rearrange_negative[number_neg1+number_negtest:])
    return train1, test1, test2, Ltrain1, Ltest1, Ltest2

In [4]:
def load_smiles(drug_names_list):
    # input drug name list
    # the smiles code list
    all_smiles_df = pd.read_csv("tox_labels_smiles_final.csv")
    smiles = all_smiles_df[all_smiles_df['drug'].isin(drug_names_list)]['smiles'].to_list()
    return smiles

In [36]:
input_folder_path = "./data/WithDrawn"

def save_data(total_seed):
    os.makedirs(input_folder_path, exist_ok=True)
    for i in range(total_seed):
        seed_folder = os.path.join(input_folder_path, f"seed_{i}")
        os.makedirs(seed_folder, exist_ok=True)
        
        train1, test1, test2, Ltrain1, Ltest1, Ltest2 = load_labels(1, i, 0.8, 0.1)
        train_smiles = load_smiles(train1)
        test1_smiles = load_smiles(test1)
        test2_smiles = load_smiles(test2)

        print(len(train1), len(Ltrain1))
        print(len(test1), len(Ltest1))
        print(len(test2), len(Ltest2))

        train_df = pd.DataFrame({'smiles': train_smiles, 'withdrawn_class': Ltrain1})
        test1_df = pd.DataFrame({'smiles': test1_smiles, 'withdrawn_class': Ltest1})
        test2_df = pd.DataFrame({'smiles': test2_smiles, 'withdrawn_class': Ltest2})
        
        train_df.to_csv(os.path.join(seed_folder, "merged_train.csv"), index=False)
        test1_df.to_csv(os.path.join(seed_folder, "merged_val.csv"), index=False)
        test2_df.to_csv(os.path.join(seed_folder, "merged_test.csv"), index=False)

In [39]:
save_data(10)

1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132
1035 1035
128 128
132 132

In [12]:
df = pd.read_csv("tox_labels.csv")
df

,drug,withdrawn,withdrawn_cards,withdrawn_liver,withdrawn_neuro,ATC_cards,ATC_liver,ATC_neuro
0,chembl479,1,1,0,0,0,0,1
1,chembl12713,1,1,0,0,0,0,1
2,chembl583,1,1,0,0,0,0,0
3,chembl17157,1,1,0,0,0,0,0
4,chembl121,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...
1290,chembl3989403,1,0,0,0,0,0,0
1291,chembl3989556,1,0,0,0,0,0,0
1292,chembl3989676,1,0,0,0,0,0,0
1293,chembl3989803,1,0,0,0,0,0,1
1294,chembl4297088,1,0,0,0,0,0,0

In [59]:
train1, test1, test2, Ltrain1, Ltest1, Ltest2 = load_labels(1, 0, 0.8, 0.1)

In [74]:
load_smiles(test2)

['CC(Cc1cccc(C(F)(F)F)c1)NCCOC(=O)c1ccccc1',
 'CC(N)C(O)c1ccccc1.Cl',
 'CCC(=O)O[C@](Cc1ccccc1)(c1ccccc1)[C@H](C)CN(C)C',
 'COc1ccc2c(C(=O)c3ccc(Cl)cc3)c(C)n(CC(=O)O)c2c1',
 'CC1CN(c2cc3c(cc2F)c(=O)c(C(=O)O)cn3-c2ccc(F)cc2F)CCN1',
 'Cc1cc2c(cc1CC(=O)c1sccc1S(=O)(=O)Nc1onc(C)c1Cl)OCO2',
 'CN(C)C/C=C(/c1ccc(Br)cc1)c1cccnc1',
 'O=C(CCNNC(=O)c1ccncc1)NCc1ccccc1',
 'Cc1nnc2n1-c1ccc(Cl)cc1C(c1ccccc1Cl)=NC2',
 'CN[C@@H]1[C@H](O[C@H]2[C@H](O[C@H]3[C@H](O)[C@@H](O)[C@H](NC(=N)N)[C@@H](O)[C@@H]3NC(=N)N)O[C@@H](C)[C@]2(O)CO)O[C@@H](CO)[C@H](O)[C@H]1O',
 'Cc1ccccc1-n1c(C)nc2ccccc2c1=O.Cl',
 'CN[C@@H]1[C@H](O[C@H]2[C@H](O[C@H]3[C@H](O)[C@@H](O)[C@H](NC(=N)N)[C@@H](O)[C@@H]3NC(=N)N)O[C@@H](C)[C@]2(O)CO)O[C@@H](CO)[C@H](O)[C@H]1O.CN[C@@H]1[C@H](O[C@H]2[C@H](O[C@H]3[C@H](O)[C@@H](O)[C@H](NC(=N)N)[C@@H](O)[C@@H]3NC(=N)N)O[C@@H](C)[C@]2(O)CO)O[C@@H](CO)[C@H](O)[C@H]1O.O=S(=O)(O)O.O=S(=O)(O)O.O=S(=O)(O)O',
 'C1CCN2C[C@H]3C[C@H](CN4CCCC[C@@H]34)[C@H]2C1',
 'O=C(Nc1ccc(Br)cc1)c1cc(Br)ccc1O',
 'Cc1cc(NC(=O)C2=C(O)c3ccccc3S(=O)(=O)N2C)no1',
 'O=C(OCC(O)CO)c1ccccc1Nc1ccnc2cc(Cl)ccc12',
 'CC(=O)Oc1c(C)cc(OCC(O)CNC(C)C)c(C)c1C',
 'CCOC(N)=O',
 'CCOC(=O)CN[C@@H](C(=O)N1CC[C@H]1C(=O)NCc1ccc(/C(N)=N\\O)cc1)C1CCCCC1',
 'NC(=O)C1CCN(CCCN2c3ccccc3Sc3ccc(Cl)cc32)CC1',
 'C=CCC1(CC(C)O)C(=O)NC(=O)NC1=O',
 'CN(C)CCN(Cc1cccs1)c1ccccn1.CN(C)CCN(Cc1cccs1)c1ccccn1.O=C(O)/C=C/C(=O)O.O=C(O)/C=C/C(=O)O.O=C(O)/C=C/C(=O)O',
 'CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)n1CC[C@@H](O)C[C@@H](O)CC(=O)[O-].CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)n1CC[C@@H](O)C[C@@H](O)CC(=O)[O-].[Ca+2]',
 'O=C1CCc2ccc(OCCCCN3CCN(c4cccc(Cl)c4Cl)CC3)cc2N1',
 'CN1CCN2c3ncccc3Cc3ccccc3C2C1',
 'O=C1CN(/N=C/c2ccc(-c3ccc([N+](=O)[O-])cc3)o2)C(=O)[N-]1.[Na+]',
 'Clc1ccc2nsnc2c1NC1=NCCN1',
 'NCCCC[C@H](N[C@@H](CCc1ccccc1)C(=O)O)C(=O)N1CCC[C@H]1C(=O)O.O.O',
 'CC(C)OC(=O)C(C)(C)Oc1ccc(C(=O)c2ccc(Cl)cc2)cc1',
 'C/C(=C\\C(=O)OCCCCCCCCC(=O)O)C[C@@H]1OC[C@H](C[C@@H]2O[C@H]2[C@@H](C)[C@H](C)O)[C@@H](O)[C@H]1O',
 'NC(=O)C[S+]([O-])C(c1ccccc1)c1ccccc1',
 'CN(C)CCOC(c1ccccc1)c1ccccc1.Cl',
 'CCOC(=O)[C@H](CCc1ccccc1)N[C@@H](C)C(=O)N1[C@H](C(=O)O)C[C@H]2CCCC[C@@H]21',
 'COc1ccc2c3c1O[C@H]1C(=O)CC[C@@]4(O)[C@@H](C2)N(C)CC[C@]314.Cl',
 'CC(C)N(CCC(C(N)=O)(c1ccccc1)c1ccccn1)C(C)C.O=P(O)(O)O',
 'CC(C)C[C@H](CN)CC(=O)O',
 'CCOC(=O)c1ccc(N)cc1',
 'CC[C@@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O)ccc3nc2-1.Cl',
 'NC(N)=Nc1nc(CSCC/C(N)=N/S(N)(=O)=O)cs1',
 'CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23',
 'Nc1ncn([C@H]2C[C@H](O)[C@@H](CO)O2)c(=O)n1',
 'Nc1ncn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c(=O)n1',
 'CN(C/C=C/c1ccccc1)Cc1cccc2ccccc12.Cl',
 'Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=C(O)C(O)C(O)C(=O)O',
 'CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12',
 'NC(=O)[C@@H]1CCCN1C(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@@H]1CCC(=O)N1',
 'C1N2CN3CN1CN(C2)C3.O=C(O)CNC(=O)c1ccccc1',
 'CS(=O)(=O)O.N[C@@H]1[C@H]2CN(c3nc4c(cc3F)c(=O)c(C(=O)O)cn4-c3ccc(F)cc3F)C[C@@H]12',
 'N=C(NCCCCCCNC(=N)NC(=N)Nc1ccc(Cl)cc1)NC(=N)Nc1ccc(Cl)cc1.O=C(O)[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO.O=C(O)[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO',
 'COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1.Cl',
 'CN1CCN(CC/C=C2/c3ccccc3Sc3ccc(S(=O)(=O)N(C)C)cc32)CC1',
 'CN1C2CCCC1CC(NC(=O)c1nn(C)c3ccccc13)C2.Cl',
 'Cc1cccc(Nc2ccncc2S(=O)(=O)NC(=O)NC(C)C)c1',
 'CCN(CC)CC#CCOC(=O)C(O)(c1ccccc1)C1CCCCC1',
 'Cl.Clc1ccc2nsnc2c1NC1=NCCN1',
 'N#Cc1ccc(C(c2ccc(C#N)cc2)n2cncn2)cc1',
 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F',
 'CCCOc1ccc(C(=O)OCCN(CC)CC)cc1N.Cl',
 'CO[C@H]1C[C@@H]2CC[C@@H](C)[C@@](O)(O2)C(=O)C(=O)N2CCCC[C@H]2C(=O)O[C@H]([C@H](C)C[C@@H]2CC[C@@H](O)[C@H](OC)C2)CC(=O)[C@H](C)/C=C(\\C)[C@@H](O)[C@@H](OC)C(=O)[C@H](C)C[C@H](C)/C=C/C=C/C=C/1C',
 'CC(=O)NCCCS(=O)(=O)[O-].CC(=O)NCCCS(=O)(=O)[O-].[Ca+2]',
 'COC(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)[C@@H](O)CN(Cc1ccc(-c2ccccn2)cc1)NC(=O)[C@@H](NC(=O)OC)C(C)(C)C)C(C)(C)C.O=S(=O)(O)O',
 'O=C1Nc2ccc(Cl)cc2[C@@](C#CC2CC2)(C(F)(F)F)O1',
 'CCCCC[C@H](O)CC[C@@H]1[C@H]2Cc3cccc(OCC(=O)O)c3C[C@H]2C[C@H]1O',
 'CCN(C)C(=O)Oc1cccc([C@H](C)N(C)C)c1',
 'CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)[C@H](CC(N)=O)NC(=O)c1ccc2ccccc2n1.CS(=O)(=O)O',
 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@@H](O)[C@H](C)O1.Cl',
 'C=CCC1(C(C)CCC)C(=O)[N-]C(=O)NC1=O.[Na+]',
 'CN[C@@H](C)[C@H](O)c1ccccc1.CN[C@@H](C)[C@H](O)c1ccccc1.O=S(=O)(O)O',
 'CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@@H](N)CSSC[C@@H](C(=O)N2CCC[C@H]2C(=O)N[C@@H](CC(C)C)C(=O)NCC(N)=O)NC(=O)[C@H](CC(N)=O)NC(=O)[C@H](CCC(N)=O)NC1=O',
 'S=P(N1CC1)(N1CC1)N1CC1',
 'C=C1/C(=C\\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)/C=C/[C@@H](O)C4CC4)CC[C@@H]23)C[C@@H](O)C[C@@H]1O',
 'CCCCc1oc2ccc(NS(C)(=O)=O)cc2c1C(=O)c1ccc(OCCCN(CCCC)CCCC)cc1',
 'CCCCC(=O)O[C@H]1CC[C@H]2[C@@H]3CCc4cc(O)ccc4[C@H]3CC[C@]12C',
 'CO/N=C(\\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)=O)CS[C@H]12)c1ccco1',
 'COC(=O)[C@@H]1CC2=CC(=O)CC[C@]2(C)[C@@]23O[C@@H]2C[C@@]2(C)[C@@H](CC[C@@]24CCC(=O)O4)[C@H]13',
 'C=CC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)/C(=N\\OCC(=O)O)c3csc(N)n3)[C@H]2SC1',
 'C=C1CC[C@@]2(O)[C@H]3Cc4ccc(O)c5c4[C@@]2(CCN3CC2CC2)[C@H]1O5.Cl',
 'Nc1nc(Cl)nc2c1ncn2[C@H]1C[C@H](O)[C@@H](CO)O1',
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21.Cl',
 'CC(C)(C)NC[C@H](O)COc1cccc2c1CCCC2=O.Cl',
 'CC(=O)Oc1cc2c(s1)CCN(C(C(=O)C1CC1)c1ccccc1F)C2.Cl',
 'Br.CN1CCC[C@@H]1Cc1c[nH]c2ccc(CCS(=O)(=O)c3ccccc3)cc12',
 'CCC(=O)NCC[C@@H]1CCc2ccc3c(c21)CCO3',
 'CCCNC(C)C(=O)Nc1ccccc1C',
 'Cl.Clc1ccccc1CN1CCc2sccc2C1',
 'CCCC(C)C1(CC)C(=O)N=C([O-])NC1=O.[Na+]',
 'CC#CCn1c(N2CCC[C@@H](N)C2)nc2c1c(=O)n(Cc1nc(C)c3ccccc3n1)c(=O)n2C',
 'CCCCCCCCCCNCCN[C@@]1(C)C[C@H](O[C@H]2[C@H](Oc3c4cc5cc3Oc3ccc(cc3Cl)[C@@H](O)[C@@H](NC(=O)[C@@H](CC(C)C)NC)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@H]5C(=O)N[C@H]3C(=O)N[C@H](C(=O)N[C@H](C(=O)O)c5cc(O)c(CNCP(=O)(O)O)c(O)c5-c5cc3ccc5O)[C@H](O)c3ccc(c(Cl)c3)O4)O[C@H](CO)[C@@H](O)[C@@H]2O)O[C@@H](C)[C@H]1O.Cl',
 'Nc1nc2ccc(OC(F)(F)F)cc2s1',
 'CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1',
 'CO[C@@]1(NC(=O)Cc2cccs2)C(=O)N2C(C(=O)O)=C(COC(N)=O)CS[C@@H]21',
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC.COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC.O=S(=O)(O)O',
 'N=C(N)c1ccc(OCCCCCOc2ccc(C(=N)N)cc2)cc1',
 'N[C@@H]1CCCCN(c2c(F)cc3c(=O)c(C(=O)O)cn(C4CC4)c3c2Cl)C1',
 'N#C[C@@H]1C[C@@H]2C[C@@H]2N1C(=O)[C@@H](N)C12CC3CC(CC(O)(C3)C1)C2.O',
 'CC(=O)c1c(C)c2cnc(Nc3ccc(N4CCNCC4)cn3)nc2n(C2CCCC2)c1=O',
 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)[O-])=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12.[Na+]',
 'CC(=O)OCC[N+](C)(C)C.[Cl-]',
 'O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2cc(O)ccc12',
 'CCOC(=O)N[C@@H]1CC[C@@H]2[C@@H](C1)C[C@H]1C(=O)O[C@H](C)[C@H]1[C@H]2/C=C/c1ccc(-c2cccc(F)c2)cn1',
 'O=NN(CCCl)C(=O)NC1CCCCC1',
 'CCCCS(=O)(=O)N[C@@H](Cc1ccc(OCCCCC2CCNCC2)cc1)C(=O)O',
 'C[C@H]1[C@H](NC(=O)/C(=N\\OC(C)(C)C(=O)O)c2csc(N)n2)C(=O)N1S(=O)(=O)O',
 'C#CCN(C)[C@H](C)Cc1ccccc1',
 'CC(C)[N+](C)(CCOC(=O)C1c2ccccc2Oc2ccccc21)C(C)C.[Br-]',
 'C/N=C(\\N)N(C)C(=N)N.Cl',
 'C=CCN.ClCC1CO1',
 'CSCCNc1nc(SCCC(F)(F)F)nc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)C(Cl)(Cl)P(=O)(O)O)[C@@H](O)[C@H]1O',
 'C=CCC1(C(C)C#CCC)C(=O)N=C([O-])N(C)C1=O.[Na+]',
 'FC(F)OC(Cl)C(F)(F)F',
 'COc1ccc2c3c1O[C@H]1C[C@@H](O)C=C[C@@]31CCN(C)C2',
 'CC1(C)NC(=O)N(c2ccc([N+](=O)[O-])c(C(F)(F)F)c2)C1=O',
 'OC[C@H]1O[C@H](O[C@]2(CO)O[C@H](CO)[C@@H](O)[C@@H]2O)[C@H](O)[C@@H](O)[C@@H]1O',
 'C[n+]1ccccc1/C=N/O.[Cl-]',
 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3CC[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3C[C@H](O)[C@]12C',
 'CCCCC[C@H](O)/C=C/[C@@H]1[C@H]2C/C(=C/CCCC(=O)O)O[C@H]2C[C@H]1O',
 'CN(C)[C@@H]1C(O)=C(C(N)=O)C(=O)[C@@]2(O)C(O)=C3C(=O)c4c(O)cccc4[C@@](C)(O)[C@H]3C[C@@H]12.Cl',
 'CO[C@@H]1[C@H](N(C)C(=O)c2ccccc2)C[C@H]2O[C@]1(C)n1c3ccccc3c3c4c(c5c6ccccc6n2c5c31)C(=O)NC4',
 'Nc1ccn(C[C@@H](CO)OCP(=O)(O)O)c(=O)n1',
 'Cl.Cn1c(CCCC(=O)O)nc2cc(N(CCCl)CCCl)ccc21',
 'CCCS(=O)(=O)Nc1ccc(F)c(C(=O)c2c[nH]c3ncc(-c4ccc(Cl)cc4)cc23)c1F',
 'Cc1[nH]c2ccccc2c1CCNCc1ccc(/C=C/C(=O)NO)cc1',
 'CN(C)c1ccc2nc3ccc(=[N+](C)C)cc-3sc2c1.O.O.O.[Cl-]',
 'COCCCN1CCC(NC(=O)c2cc(Cl)c(N)c3c2OCC3)CC1',
 'CC1(C)S[C@@H]2[C@H](NC(=O)Cc3ccccc3)C(=O)N2[C@H]1C(=O)O',
 'CC(=O)N[C@H](Cc1ccc2ccccc2c1)C(=O)N[C@H](Cc1ccc(Cl)cc1)C(=O)N[C@H](Cc1cccnc1)C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)N[C@H](CCCNC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@H](C)C(N)=O.CC(=O)O',
 'Nc1nc(N)c2nc(-c3ccccc3)c(N)nc2n1',
 'CS(=O)(=O)O.Oc1ccc(C2CNCCc3c2cc(O)c(O)c3Cl)cc1',
 'CC(Oc1c(Cl)cccc1Cl)C1=NCCN1.Cl',
 'O=C([O-])CCCO.[Na+]',
 'Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)cc1C#Cc1cnc2cccnn12.Cl',
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CC[C@H]2C)c1']

In [40]:
def load_data(based_data_path):
    # based_data_path = "./data/WithDrawn"
    train_data_path = os.path.join(based_data_path, 'merged_train.csv')
    val_data_path = os.path.join(based_data_path, 'merged_val.csv')
    test_data_path = os.path.join(based_data_path, 'merged_test.csv')
    
    train_df = pd.read_csv(train_data_path, usecols=['smiles', 'withdrawn_class'])
    train_df['type'] = 'train'

    val_df = pd.read_csv(val_data_path, usecols=['smiles', 'withdrawn_class'])
    val_df['type'] = 'val'

    test_df = pd.read_csv(test_data_path, usecols=['smiles', 'withdrawn_class'])
    test_df['type'] = 'test'

    raw_df = pd.concat([train_df, val_df, test_df])
    
    return raw_df

In [41]:
def prepare_input(row, source_file, target_file):
    print(row['smiles'], file=source_file)
    print(row['withdrawn_class'], file=target_file)

In [42]:
os.makedirs(input_folder_path, exist_ok=True)
for i in range(10):
    input_folder_path = os.path.join("./data/WithDrawn", f'seed_{i}')
    input_source_dict = {}
    input_target_dict = {}
    raw_df = load_data(input_folder_path)
    for data_type in ['train', 'val', 'test']:
        input_source_dict[data_type] = open(os.path.join(input_folder_path, data_type + ".source"), 'w')
        input_target_dict[data_type] = open(os.path.join(input_folder_path, data_type + ".target"), 'w')
    for i, item in raw_df.iterrows():
        data_type = item['type']
        prepare_input(item, input_source_dict[data_type], input_target_dict[data_type])

    for key, val in input_source_dict.items():
        val.close()
    for key, val in input_target_dict.items():
        val.close()

## Repetitive Train Predict

In [6]:
pre_train_model = '/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple'

In [ ]:
input_folder_path = os.path.join(based_data_path, "data/WithDrawn", "seed_1")
# os.makedirs(os.path.join(based_data_path, "model", "seed_1"), exist_ok=True)
output_folder_path = os.path.join(based_data_path, "model", "seed_1")

train = "t5chem train --data_dir %s --output_dir %s --num_classes %s --pretrain %s --task_type classification --num_epoch %s" % (input_folder_path, output_folder_path, 2, pre_train_model, 30)
# os.environ['WANDB_DISABLED'] = "true"
os.system(train)

Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 0}.
wandb: Currently logged in as: wangyf99 (wangyf99-icahn-school-of-medicine-at-mount-sinai) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: setting up run lei9wqhw
wandb: Tracking run with wandb version 0.23.0
wandb: Run data is saved locally in /Users/alexwang/Documents/GitHub/withDRAWN/wandb/run-20260513_140406-lei9wqhw
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run 0513_1404_classification
wandb: ⭐️ View project at https://wandb.ai/wangyf99-icahn-school-of-medicine-at-mount-sinai/T5Chem
wandb: 🚀 View run at https://wandb.ai/wangyf99-icahn-school-of-medicine-at-mount-sinai/T5Chem/runs/lei9wqhw

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_1', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_1', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=30, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x173586840>)

  0%|                                                  | 0/990 [00:00<?, ?it/s]/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
  2%|▉                                        | 23/990 [00:21<26:05,  1.62s/it]

In [47]:
based_data_path = '/Users/alexwang/Documents/GitHub/withDRAWN'
pre_train_model = '/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple'
input_folder_path = os.path.join(based_data_path, "data/WithDrawn", "seed_0")
# os.makedirs(os.path.join(based_data_path, "model", "seed_1"), exist_ok=True)
output_folder_path = os.path.join(based_data_path, "model", "seed_0")

train = "t5chem train --data_dir %s --output_dir %s --num_classes %s --pretrain %s --task_type classification --num_epoch %s" % (input_folder_path, output_folder_path, 2, pre_train_model, 100)
os.environ['WANDB_DISABLED'] = "true"
os.system(train)

Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_0', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_0', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=100, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x30483e840>)

256

In [48]:
import sys
print(sys.executable)

/opt/anaconda3/bin/python

In [32]:
input_folder_path = os.path.join("/Users/alexwang/Documents/GitHub/DrugWithdrawn/data/drug_withdrawn", 'db_agree_dups', 'DrugBank')
# os.makedirs(os.path.join(based_data_path, "model", "seed_1"), exist_ok=True)
output_folder_path = os.path.join("/Users/alexwang/Documents/GitHub/DrugWithdrawn/model", 'db_agree_dups', 'DrugBank')

train = "t5chem train --data_dir %s --output_dir %s --num_classes %s --pretrain %s --task_type classification --num_epoch %s" % (input_folder_path, output_folder_path, 2, pre_train_model, 100)

os.system(train)

Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/DrugWithdrawn/data/drug_withdrawn/db_agree_dups/DrugBank', output_dir='/Users/alexwang/Documents/GitHub/DrugWithdrawn/model/db_agree_dups/DrugBank', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=100, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x13c286840>)

256

In [27]:
os.makedirs(os.path.join(based_data_path, "model", "seed_1"), exist_ok=True)

In [26]:
os.system("find /Users/alexwang/Documents/GitHub/withDRAWN -name 'pytorch_model.bin')

SyntaxError: unterminated string literal (detected at line 1) (3514901013.py, line 1)

In [17]:
for i in range(10):
        input_folder_path = os.path.join(based_data_path, "data/WithDrawn", f"seed_{i}")
        os.makedirs(os.path.join(based_data_path, "model", f"seed_{i}"), exist_ok=True)
        output_folder_path = os.path.join(based_data_path, "model", f"seed_{i}")
    
        train = "t5chem train --data_dir %s --output_dir %s --num_classes %s --pretrain %s --task_type classification --num_epoch %s" % (input_folder_path, output_folder_path, 2, pre_train_model, 3)
        # os.environ['WANDB_DISABLED'] = "true"
        os.system(train)

        model_folder_path = os.path.join(based_data_path, "model", f"seed_{i}")
        pred_output_path = os.path.join(based_data_path, "model", f"seed_{i}", "raw_prob.csv")
        predict = 't5chem predict --data_dir %s --model_dir %s --prediction %s' % (input_folder_path, model_folder_path, pred_output_path)
        os.system(predict)

Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_0', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_0', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x170b9a840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_1', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_1', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x17c7ea840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_2', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_2', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x17bade840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_3', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_3', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x16fc06840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_4', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_4', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x16757e840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_5', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_5', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x16557e840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_6', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_6', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x303c66840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_7', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_7', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x17828a840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_8', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_8', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x30079e840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'
Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/WithDrawn/seed_9', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model/seed_9', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=3, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x14b8be840>)

Traceback (most recent call last):
  File "/opt/anaconda3/bin/t5chem", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
    ~~~~~~~^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_prediction.py", line 75, in predict
    task = T5ChemTasks[config.task_type]
                       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: 'T5Config' object has no attribute 'task_type'

In [8]:
import os
for i in range(10):
    path = os.path.join(based_data_path, "data/drug_withdrawn", f"seed_{i}")
    print(path, os.path.exists(path))
    if os.path.exists(path):
        print(os.listdir(path))

/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_0 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_1 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_2 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_3 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_4 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_5 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_6 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_7 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_8 False
/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn/seed_9 False

# Train

here we point to the path of the pre-trained model
and then train t5chem for each evaluation and each test dataset

In [15]:
pre_train_model = '/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple'

In [21]:
input_folder_path = os.path.join(based_data_path, "data/drug_withdrawn")
output_folder_path = os.path.join(based_data_path, "model")
train = "t5chem train --data_dir %s --output_dir %s --num_classes %s --pretrain %s --task_type classification --num_epoch %s" % (input_folder_path, output_folder_path, 2, pre_train_model, 10)
os.environ["WANDB_DISABLED"] = "true"
os.system(train)
ret = os.system(train)
print("Exit code:", ret)

Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=10, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x15d982840>)

Some weights of T5ForProperty were not initialized from the model checkpoint at /Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/anaconda3/lib/python3.13/site-packages/t5chem/run_trainer.py:274: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Namespace(data_dir='/Users/alexwang/Documents/GitHub/withDRAWN/data/drug_withdrawn', output_dir='/Users/alexwang/Documents/GitHub/withDRAWN/model', task_type='classification', run_name='', pretrain='/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=10, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=2, command=<function train at 0x16a622840>)
Exit code: 256

# Predict

here we predict and evaluate all the metrics for our t5chem model for all split and test datasets

In [94]:
pre_train_model = '/Users/alexwang/Documents/GitHub/DrugWithdrawn/models/pretrain/simple'

In [18]:

input_folder_path = os.path.join(based_data_path, "data/drug_withdrawn")
model_folder_path = os.path.join(based_data_path, "model")
pred_output_path = os.path.join(based_data_path, "model", 'raw_prob.csv')
predict = 't5chem predict --data_dir %s --model_dir %s --prediction %s' % (input_folder_path, model_folder_path, pred_output_path)

os.system(predict)

prediction: 100%|████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]

Accuracy: 75.0%

0

In [96]:
def load_test(model_path):
    df = pd.read_csv(os.path.join(model_path, 'raw_prob.csv'))
    return df

In [97]:
import numpy as np
from sklearn.metrics import precision_recall_curve, roc_curve, auc, average_precision_score
from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef, roc_auc_score, average_precision_score, accuracy_score

def get_scores(df):
    # print(df['target'].tolist())
    y = np.array(df['target'].tolist())
    pred = np.array(df['prediction_1'].tolist())
    fpr, tpr, thresholds = roc_curve(y, pred)
    precision, recall, thresholds = precision_recall_curve(y, pred)
    mcc = matthews_corrcoef(y_true=y, y_pred=(pred > 0.5))
    tn, fp, fn, tp = confusion_matrix(y_true=y, y_pred=(pred > 0.5)).ravel()
    specificity = tn / (tn+fp)
    sensitivity = tp / (tp+fn)
    recall = sensitivity
    precision = tp / (tp + fp)
    roc = roc_auc_score(y, pred)
    aupr = average_precision_score(y, pred)
    acc = accuracy_score(y_true=y, y_pred=(pred > 0.5))
    f1 = 2 * (precision * recall) / (precision + recall)
    return {'auroc': auc(fpr, tpr),'auprc': aupr,'roc': roc,'acc': acc,'mcc': mcc,'sp': specificity,'sn': sensitivity, 'f1': f1, 'precision': precision}

In [98]:
final_scores_df = pd.DataFrame(columns=['auprc', 'auroc', 'f1', 'precision', 'roc', 'acc', 'mcc', 'sp', 'sn', 'folder', 'modal'])

input_folder_path = os.path.join(based_data_path, "model")
df = load_test(input_folder_path)

dic = get_scores(df)
#dic.update({'folder': folder, 'modal': modal})
final_scores_df.loc[len(final_scores_df)] = pd.Series(dic)

In [99]:
final_scores_df

    auprc  auroc    f1  precision   roc   acc  mcc    sp    sn  folder  modal
0  0.6875   0.75  0.75       0.75  0.75  0.75  0.5  0.75  0.75     NaN    NaN

In [33]:
{'hello': 1}.update({'world':2})

In [34]:
from transformers import T5ForConditionalGeneration
from t5chem import T5ForProperty, SimpleTokenizer
import os
import torch
from tqdm.auto import tqdm
sm = torch.nn.Softmax(dim=1)

final_scores_df = pd.DataFrame(columns=['auprc', 'auroc', 'roc', 'acc', 'mcc', 'sp', 'sn', 'folder', 'modal'])
for folder in ['db_agree_no_dups', 'db_agree_dups']:
    for modal in ['ChEMBL', 'DrugBank',' NCATS']:
        input_folder_path = os.path.join("./data/drug_withdrawn", folder, modal)
        model_folder_path = os.path.join("./model", folder, modal)
        tokenizer = SimpleTokenizer(vocab_file=os.path.join(model_folder_path, 'vocab.pt'))
        model = T5ForProperty.from_pretrained(model_folder_path)  # for non-seq2seq task
        df = load_test(input_folder_path, model_folder_path)
        probs = []
        for i, row in tqdm(df.iterrows()):
            inputs = tokenizer.encode("Classification:" + row['smiles'], return_tensors='pt')
            outputs = model(inputs)
            probs.append(sm(outputs.logits)[0][-1].detach().numpy().item())
        df['prob'] = probs
        df.to_csv(os.path.join(model_folder_path, 'preds.csv'))
        dic = get_scores(df)
        dic.update({'folder': folder, 'modal': modal})
        final_scores_df.loc[len(final_scores_df)] = pd.Series(dic)
#         final_scores_df = pd.concat([final_scores_df, pd.DataFrame([pd.Series(dic)])], ignore_index=True)
#         final_scores_df = final_scores_df.append(pd.Series(dic), ignore_index=True)

FileNotFoundError: Vocabulary file not found at ./model/db_agree_no_dups/ChEMBL/vocab.pt

In [ ]:
final_scores_df

In [ ]:
final_scores_df.to_csv('./T5chem_final_results.csv', index=False)